routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrackingNumberController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    $order_number = 'ordernumber';
    $email = 'email';
    $zipcode = 'zipcode';
    return view('orderWelcome', compact('order_number', 'email', 'zipcode'));
});
Route::match(['get','post'],"/trackinginformation/{order_number}/{email}/",'TrackingNumberController@saveApiData')->name('order.number');

// vanaf hier komt het admin gedeelte
Route::resource('admin' ,'carriersController')->middleware('auth');

Route::resource('blog' ,'BlogController');

//dit is de route voor de statussen
Route::resource('status' ,'statusController')->middleware('auth');
//dit is de route voor de substatussen
Route::resource('substatus', 'subStatusController')->middleware('auth');
//dit is de route voor de substatusdescriptions
Route::resource('substatusdescription', 'SubStatusDescriptionController')->middleware('auth');

//De api route
Route::get('/apicarriers', 'carriersController@getApi')->name('api.carrier.list');

Route::get('/time', 'TrackingNumberController@time')->name('time');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Substatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Substatus extends Model
{
    //
    protected $fillable = [
        'substatuscode','status_code','description'
    ];
}

app/Http/Controllers/subStatusController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubStatusRequest;
use App\Status;
use App\Substatus;
use Illuminate\Http\Request;

class subStatusController extends Controller
{
    public function index()
    {
        $substatuses = Substatus::paginate(5);
//            ->with('tags')
//            ->orderBy('id', 'ASC')
//            ->paginate(3);
        return view('substatus.index', compact('substatuses'));
    }

    public function destroy($id)
    {
        Substatus::find($id)->delete();

        return redirect()->route('substatus.index')
            ->with('success','Product deleted successfully');
    }

    public function create(Status $status)
    {
        $status = Status::all();
        return view('substatus.create', compact('status'));
    }

    /**
     * Store with regex
     *
     * @param  \App\Http\Requests\SubStatusRequest  $request
     * @return Illuminate\Http\Response
     */

    public function store(SubStatusRequest $request)
    {
        Substatus::create($request->all());

        return redirect()->route('substatus.index')
            ->with('success','Substatus created successfully.');
    }

    public function edit($id)
    {
        $substatus = Substatus::find($id);
        return view('substatus.edit',compact('substatus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     */
    public function update(Request $request,$id)
    {
        Substatus::find($id)->update($request->all());

        return redirect()->route('substatus.index')
            ->with('success','Item updated successfully');
    }

}

resources/views/substatus/create.blade.php
@extends('layouts.create')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New substatus</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('substatus.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('substatus.store') }}" method="POST">
        @csrf
        <label>Code:</label>
        <input type="text" class="form-control" name="substatuscode" id="substatuscode" value="{{old('substatuscode')}}">
        <label>status code:</label>
        <select value="{{old('status_code')}}" name="status_code" id="status_code" class="form-control">
            @foreach ($status as $statuses)
                <option value="{{$statuses->code}}">{{$statuses->code}}</option>
            @endforeach
        </select><span class="pmd-textfield-focused"></span>
                <label>Description:</label>
                <input type="text" class="form-control w-50" name="description" id="description" value="{{old('description')}}" size="50">
        <br>
        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
@endsection

resources/views/substatus/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit current substatus</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('substatus.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
    {!! Form::model($substatus, ['method' => 'PATCH','route' => ['substatus.update', $substatus->id]]) !!}
        @csrf
        <label>Code:</label>
        <input type="text" class="form-control" name="code" id="code" value="{{$substatus->code}}">
        <label>Description</label>
        <input type="text" class="form-control" name="description" id="description" value="{{$substatus->description}}">
        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/substatus/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Substatus</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('substatus.create') }}"> Create substatus</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Hours</th>
            <th>Action</th>
        </tr>
        @foreach ($substatuses as $substatus)
            <tr>
                <td>{{ $substatus->status_code }}</td>
                <td>{{ $substatus->description }}</td>
                <td>{{ $substatus->hours ?? 'Instantly' }}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE','route' => ['substatus.destroy', $substatus->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}

                    <a class="btn btn-primary" href="{{ route('substatus.edit',$substatus->id) }}">Edit</a>
                </td>
            </tr>
    @endforeach
    </table>
    {{ $substatuses->links('pagination::bootstrap-4') }}
@endsection

resources/views/substatus/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 6 CRUD Application - ItSolutionStuff.com</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/substatus/substatus.blade.php
@extends('layouts.app')

@section('content')
@endsection