routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrackingNumberController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    $order_number = 'ordernumber';
    $email = 'email';
    $zipcode = 'zipcode';
    return view('orderWelcome', compact('order_number', 'email', 'zipcode'));
});
Route::match(['get','post'],"/trackinginformation/{order_number}/{email}/",'TrackingNumberController@saveApiData')->name('order.number');

// vanaf hier komt het admin gedeelte
Route::resource('admin' ,'carriersController')->middleware('auth');

Route::resource('blog' ,'BlogController');

//dit is de route voor de statussen
Route::resource('status' ,'statusController')->middleware('auth');
//dit is de route voor de substatussen
Route::resource('substatus', 'subStatusController')->middleware('auth');
//dit is de route voor de substatusdescriptions
Route::resource('substatusdescription', 'SubStatusDescriptionController')->middleware('auth');

//De api route
Route::get('/apicarriers', 'carriersController@getApi')->name('api.carrier.list');

Route::get('/time', 'TrackingNumberController@time')->name('time');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Carrier</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('admin.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('admin.store') }}" method="POST">
        @csrf
        <label>Name:</label>
        <input type="text" class="form-control" name="name" id="name" value="{{old('name')}}">

        <label>Code:</label>
        <input type="text" class="form-control" name="code" id="code" value="{{old('code')}}">

        <label>Country</label>
        <select value="{{old('country')}}" name="country" class="form-control">
            <option value="">Select Country</option>
            @foreach ($countries as $countries)
                <option value="{{$countries->name}}">{{$countries->name}}</option>
            @endforeach
        </select><span class="pmd-textfield-focused"></span>

        <label>Homepage:</label>
        <input type="text" class="form-control" name="homepage" id="homepage" value="{{old('homepage')}}">

        <label>Type:</label>
        <input type="text" class="form-control" name="type" id="type" value="{{old('type')}}">

        <label>Phone:</label>
        <input type="text" class="form-control" name="phone" id="phone" value="{{old('phone')}}">

        <label>Picture:</label>
        <input type="text" class="form-control" name="picture" id="picture" value="{{old('picture')}}">

        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit current carrier</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('admin.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
    {!! Form::model($carrier, ['method' => 'PATCH','route' => ['admin.update', $carrier->id]]) !!}
        @csrf
        <label>Name:</label>
        <input type="text" class="form-control" name="name" id="name" value="{{$carrier->name}}">
        <label>Code:</label>
        <input type="text" class="form-control" name="code" id="code" value="{{$carrier->code}}">
        <label>Country</label>
        <select value="{{old('country')}}" name="country" class="form-control">
            <option value="">{{$carrier->country}}</option>
            @foreach ($countries as $countries)
                <option value="{{$countries->name}}">{{$countries->name}}</option>
            @endforeach
        </select><span class="pmd-textfield-focused"></span>

        <label>Type:</label>
        <input type="text" class="form-control" name="type" id="type" value="{{$carrier->type}}">

        <label>Type:</label>
        <input type="text" class="form-control" name="type" id="type" value="{{$carrier->homepage}}">

        <label>Type:</label>
        <input type="text" class="form-control" name="type" id="type" value="{{$carrier->phone}}">

        <label>Type:</label>
        <input type="text" class="form-control" name="type" id="type" value="{{$carrier->picture}}">

        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Carriers</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{route('api.carrier.list')}}" onclick="loader()">Get a full updated list from carriers</a>
            </div>
        </div>
    </div>
    <div class="spinner spinner-border text-primary" id="loader" hidden></div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Code</th>
            <th>Country</th>
            <th>Type</th>
            <th>Homepage</th>
            <th>Phone</th>
            <th>Picture</th>
            <th>Action</th>
        </tr>
        @foreach ($carriers as $carrier)
            <tr>
                <td>{{ $carrier->name }}</td>
                <td>{{ $carrier->code }}</td>
                <td>{{ $carrier->country }}</td>
                <td>{{ $carrier->type }}</td>
                <td><a href="{{ $carrier->homepage }}">{{ $carrier->name }}</a> </td>
                <td>{{ $carrier->phone }}</td>
                <td><img src="{{ $carrier->picture }}" height="100px" width="100px"> </td>
                <td>
                    {!! Form::open(['method' => 'DELETE','route' => ['admin.destroy', $carrier->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}

                        <a class="btn btn-primary" href="{{ route('admin.edit',$carrier->id) }}">Edit</a>
                </td>
            </tr>
        @endforeach
    </table>
    {{ $carriers->links('pagination::bootstrap-4') }}
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 6 CRUD Application - ItSolutionStuff.com</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/admin/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('admin.index') }}"> Back</a>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p class="font-weight-bold">
                            Name: {{ $carrier->name }}
                            <br>
                            code : {{$carrier->code}}
                            <br>
                            country : {{ $carrier->country}}
                            <br>
                            Type : {{$carrier->type}}
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection