routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrackingNumberController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    $order_number = 'ordernumber';
    $email = 'email';
    $zipcode = 'zipcode';
    return view('orderWelcome', compact('order_number', 'email', 'zipcode'));
});
Route::match(['get','post'],"/trackinginformation/{order_number}/{email}/",'TrackingNumberController@saveApiData')->name('order.number');

// vanaf hier komt het admin gedeelte
Route::resource('admin' ,'carriersController')->middleware('auth');

Route::resource('blog' ,'BlogController');

//dit is de route voor de statussen
Route::resource('status' ,'statusController')->middleware('auth');
//dit is de route voor de substatussen
Route::resource('substatus', 'subStatusController')->middleware('auth');
//dit is de route voor de substatusdescriptions
Route::resource('substatusdescription', 'SubStatusDescriptionController')->middleware('auth');

//De api route
Route::get('/apicarriers', 'carriersController@getApi')->name('api.carrier.list');

Route::get('/time', 'TrackingNumberController@time')->name('time');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Substatusdescription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Substatusdescription extends Model
{
    use HasFactory;

    protected $fillable = [
        'substatuscode','hours','description','percentage'
    ];
}

app/Http/Controllers/SubStatusDescriptionController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\SubstatusDescriptionRequest;
use App\Status;
use App\Substatus;
use App\Substatusdescription;
use Illuminate\Http\Request;

class SubStatusDescriptionController extends Controller
{
    public function index()
    {
        $subStatusDescriptions = Substatusdescription::paginate(5);
//            ->with('tags')
//            ->orderBy('id', 'ASC')
//            ->paginate(3);
        return view('substatusdescription.index', compact('subStatusDescriptions'));
    }
//
    public function destroy($id)
    {
        Substatusdescription::find($id)->delete();

        return redirect()->route('substatusdescription.index')
            ->with('success','Substatus Description deleted successfully');
    }
//
    public function create(Substatus $substatus)
    {
//        $this->authorize('create');
        $substatus = Substatus::all();
        $status = Status::all();
        return view('substatusdescription.create', compact('substatus','status'));
    }
//

    /**
     * Store with regex
     *
     * @param SubstatusDescriptionRequest $request
     * @return Illuminate\Http\Response
     */

    public function store(SubstatusDescriptionRequest $request)
    {
        Substatusdescription::create($request->all());

        return redirect()->route('substatusdescription.index')
            ->with('success','Substatus Description created successfully.');
    }

    public function edit($id)
    {
        $substatusdescription = Substatusdescription::find($id);
        $substatus = Substatus::all();
        return view('substatusdescription.edit',compact('substatusdescription', 'substatus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,$id)
    {
        Substatusdescription::find($id)->update($request->all());

        return redirect()->route('substatusdescription.index')
            ->with('success','Substatus Description updated successfully');
    }

}

resources/views/substatusdescription/create.blade.php
@extends('layouts.create')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Substatus Description!</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('substatusdescription.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('substatusdescription.store') }}" method="POST">
        @csrf
        <label>SubStatus code:</label>
        <select value="{{old('substatuscode')}}" name="substatuscode" id="substatuscode" class="form-control" >
            <option value="">Select Substatus code</option>
            @foreach ($substatus as $substatuses)
                <option value="{{$substatuses->substatuscode}}">{{$substatuses->substatuscode}}</option>
            @endforeach
        </select><span class="pmd-textfield-focused"></span>
        <br>
        <label>Description:</label>
        <br>
        <div class="row">
                <input type="text" class="form-control w-75 r-0" name="description" id="description"  style="margin: 0px; padding: 0px;" value="{{old('Description')}}">
                <input type="number" class="form-control w-25 r-0" name="hours" value="{{old('hours')}}" placeholder="Hours">
        </div>
        <br>
        <label>Percentage %</label>
        <input type="number" class="form-control w-25 r-0" name="percentage" value="{{old('percentage')}}" placeholder="percentage">

        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
@endsection

resources/views/substatusdescription/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit {{$substatusdescription->substatuscode}} Description</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('substatusdescription.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
    {!! Form::model($substatusdescription, ['method' => 'PATCH','route' => ['substatusdescription.update', $substatusdescription->id]]) !!}
        @csrf
        <label>status code:</label>
        <select value="{{old('substatuscode')}}" name="substatuscode" id="substatuscode" class="form-control">
            <option value="{{$substatusdescription->substatuscode}}">{{$substatusdescription->substatuscode}}</option>
            @foreach ($substatus as $substatuses)
                <option value="{{$substatuses->code}}">{{$substatuses->code}}</option>
            @endforeach
        </select><span class="pmd-textfield-focused"></span>
        <br>


        <label>Description</label>
        <div class="row">
            <input type="text" class="form-control w-50 r-0" name="description" id="description" value="{{$substatusdescription->description}}">
            <input type="number" class="form-control w-25 r-0" name="hours" id="hours" value="{{$substatusdescription->hours}}">
        </div>
        <br>
        <label>Percentage %</label>
        <input type="number" class="form-control w-25 r-0" name="hours" id="hours" value="{{$substatusdescription->percentage}}">
        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/substatusdescription/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Substatus Description</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{route('substatusdescription.create')}}"> Create a new Substatus Description!</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Hours</th>
            <th>Percentage</th>
            <th>Action</th>
        </tr>
        @foreach ($subStatusDescriptions as $subStatusDescription)
            <tr>
                <td>{{ $subStatusDescription->substatuscode }}</td>
                <td>{{ $subStatusDescription->description }}</td>
                <td>{{ $subStatusDescription->hours}}</td>
                <td>{{ $subStatusDescription->percentage}}%</td>
                <td>
                    {!! Form::open(['method' => 'DELETE','route' => ['substatusdescription.destroy', $subStatusDescription->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                    <a class="btn btn-primary" href="{{ route('substatusdescription.edit',$subStatusDescription->id) }}">Edit</a>
                </td>
            </tr>
    @endforeach
    </table>
    {{ $subStatusDescriptions->links('pagination::bootstrap-4') }}
@endsection