routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrackingNumberController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    $order_number = 'ordernumber';
    $email = 'email';
    $zipcode = 'zipcode';
    return view('orderWelcome', compact('order_number', 'email', 'zipcode'));
});
Route::match(['get','post'],"/trackinginformation/{order_number}/{email}/",'TrackingNumberController@saveApiData')->name('order.number');

// vanaf hier komt het admin gedeelte
Route::resource('admin' ,'carriersController')->middleware('auth');

Route::resource('blog' ,'BlogController');

//dit is de route voor de statussen
Route::resource('status' ,'statusController')->middleware('auth');
//dit is de route voor de substatussen
Route::resource('substatus', 'subStatusController')->middleware('auth');
//dit is de route voor de substatusdescriptions
Route::resource('substatusdescription', 'SubStatusDescriptionController')->middleware('auth');

//De api route
Route::get('/apicarriers', 'carriersController@getApi')->name('api.carrier.list');

Route::get('/time', 'TrackingNumberController@time')->name('time');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'question',
        'answer',
        'urgency',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\BlogRequest;
use App\Http\Requests\SubstatusDescriptionRequest;
use App\Models\Blog;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['only' => 'create']);
    }

    public function index()
    {
        $search = \Request::get('search');  //the param of URI
        $blog = Blog::where('question', 'like', '%'.$search.'%')
            ->orderBy('urgency')
            ->paginate();
        return view('blog.index', compact('blog'));

    }
    public function destroy($id)
    {
        Blog::find($id)->delete();

        return redirect()->route('blog.index')
            ->with('success','Question deleted successfully');
    }
//
    public function create()
    {
        return view('blog.create');
    }
//

    /**
     * Store with regex
     *
     * @param BlogRequest $request
     * @return RedirectResponse
     */

    public function store(BlogRequest $request)
    {
        Blog::create($request->all());

        return redirect()->route('blog.index')
            ->with('success','Question created successfully.');
    }

    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('blog.edit',compact('blog'));
    }
    public function show($id)
    {
        $blog = Blog::find($id);
        return view('blog.show',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     */
    public function update(Request $request,$id)
    {
        Blog::find($id)->update($request->all());

        return redirect()->route('blog.index')
            ->with('success','Blog Description updated successfully');
    }
}

resources/views/blog/create.blade.php
@extends('layouts.create')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Question</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('blog.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('blog.store') }}" method="POST">
        @csrf
        <label>Title:</label>
        <input type="text" class="form-control" name="title" id="title" value="{{old('title')}}">

        <label>Question:</label>
        <input type="text" class="form-control" name="question" id="question" value="{{old('question')}}">

        <label>Answer:</label>
        <input type="text" class="form-control" name="answer" id="answer" value="{{old('answer')}}">

        <label>Urgency:</label>
        <input type="text" class="form-control" name="urgency" id="urgency" value="{{old('urgency')}}" placeholder="1 is the highest urgency">

        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit {{$blog->title}}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('blog.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        {!! Form::model($blog, ['method' => 'PATCH','route' => ['blog.update', $blog->id]]) !!}
        @csrf
        <label>Title:</label>
        <input type="text" class="form-control" name="title" id="title" value="{{$blog->title}}">
        <label>Question:</label>
        <input type="text" class="form-control" name="question" id="question" value="{{$blog->question}}">
        <label>Answer::</label>
        <input type="text" class="form-control" name="answer" id="answer" value="{{$blog->answer}}">
        <button type="submit" class="btn btn-primary">Submit
        </button>
        </form>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>FAQ</h2>
            </div>
        </div>
    </div>
    @if (Auth::check())
    <div class="pull-right">
        <a class="btn btn-success" href="{{ route('blog.create') }}"> Create blog</a>
    </div>
    @endif

    {!! Form::open(['method'=>'GET','url'=>'blog','class'=>'navbar-form navbar-left','role'=>'search'])  !!}
    <div class="input-group custom-search-form">
        <input type="text" class="form-control" name="search" placeholder="Search...">
        <span class="input-group-btn">
        <a class="btn btn-success"> Search</a>
</span>
        {!! Form::close() !!}
    @foreach ($blog as $blogs)
        <br>
        <br>
    <div class="card" style="position: relative;
    display: inline-table;
    flex-wrap: wrap;
    align-items: stretch;
    width: 100%;}">
        <div class="card">
        <div class="card-header">
            <a href="{{route('blog.show', $blogs->id)}}"><h5 style="color: #1b1e21" class="card-title"><b>{{$blogs->title}}</b></h5></a>
        </div>
        <div class="card-body" style="color: black">{{$blogs->question}}</div>
        @if (Auth::check())
        <div class="card-footer">
            <a class="btn btn-primary" href="{{ route('blog.edit',$blogs->id) }}">Edit</a>
            {!! Form::open(['method' => 'DELETE','route' => ['blog.destroy', $blogs->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>
            @endif
    </div>

     @endforeach
@endsection

resources/views/blog/show.blade.php
@extends('layouts.create')

@section('content')

    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('blog.index') }}"> Back</a>
    </div>

    <div class="card" style="width: 80rem;
                             text-align: center;
                             position:absolute;
                             right:250px;
                             top:250px;">
        <div class="card-header">
        <h5 class="card-title" style="color: black;">{{$blog->question}}</h5>
        </div>
        <div class="card-body">
            <p class="card-text" style="color: black">{{$blog->answer}}</div>
    </div>
@endsection